"""Reviewed public-export baseline; never regenerated from the implementation."""

CORE_PUBLIC_API = {
    "run_agent_loop",
    "AgentLoopConfig",
    "ToolExecutionConfig",
    "AgentTool",
    "ToolCallContext",
    "AgentToolResult",
    "AgentLoopResult",
    "AgentMessage",
    "AssistantMessage",
    "CustomMessage",
    "ImageBlock",
    "StopReason",
    "TextBlock",
    "ThinkingBlock",
    "ToolCallBlock",
    "ToolResultMessage",
    "Usage",
    "UserMessage",
    "HookRegistry",
    "ExecutionEnv",
    "Session",
    "Result",
    "TaggedError",
    "OverflowError",
    "RetryableError",
    "FatalError",
    "ValidationError",
    "SessionCorruptError",
    "Provider",
    "ContextReducer",
    "SessionLike",
    "ContextTrigger",
    "ContextItem",
    "ContextSnapshot",
    "ContextDecision",
    "ParameterKind",
    "MechanismLayer",
    "MechanismFamily",
    "ContextPhase",
    "ActivationScope",
    "ParameterDescriptor",
    "MechanismContribution",
    "MechanismEffects",
    "MechanismDescriptor",
    "ContextProvenance",
    "ContextFrame",
    "ContextTransform",
    "ContextTransformer",
    "ContextStage",
    "ContextPipelineProfile",
    "ContextPipeline",
}

DATA_MODEL_PUBLIC_API = {
    "TextBlock",
    "ThinkingBlock",
    "ToolCallBlock",
    "ImageBlock",
    "ContentBlock",
    "block_from_dict",
    "StopReason",
    "Usage",
    "CUSTOM_KIND_COMPACTION",
    "CUSTOM_KIND_BRANCH",
    "UserMessage",
    "AssistantMessage",
    "ToolResultMessage",
    "CustomMessage",
    "AgentMessage",
    "message_from_dict",
    "AgentToolResult",
    "AgentLoopResult",
    "encode_image_bytes",
    "AgentLoopContext",
    "ProviderView",
    "BeforeToolCallResult",
    "ContextTrigger",
    "ContextItem",
    "ContextSnapshot",
    "ContextDecision",
}

ENV_CONTRACT_PUBLIC_API = {
    "ExecOptions",
    "ExecResult",
    "ExecutionEnv",
    "FileInfo",
    "FileSystem",
    "Shell",
}

LAB_ENV_PUBLIC_API = {"LocalEnv"}

MODULE_EXPORTS = {
    "fruitfly_agent.interactive": {
        "AgentApplication",
        "ApplicationState",
        "ConfigurationActionResult",
        "ConfigurationController",
        "ConfigurationLaunchResult",
        "ConfigurationMechanism",
        "ConfigurationParameter",
        "ConfigurationSnapshot",
        "InteractiveMechanism",
        "InteractiveSession",
        "RuntimeFactory",
        "RuntimeHandle",
        "TerminalConfigurationFrontend",
        "TerminalFrontend",
    },
    "fruitfly_agent.core.env": ENV_CONTRACT_PUBLIC_API,
    "fruitfly_agent.core.env.types": {"ExecOptions", "ExecResult", "FileInfo"},
    "fruitfly_agent.core.env.protocols": {"ExecutionEnv", "FileSystem", "Shell"},
    "fruitfly_agent.lab": {
        "InformationHub",
        "InformationQuery",
        "LocalEnv",
        "Skill",
        "SummarizingCompactor",
        "SummarizingCompactorConfig",
        "builtin_tools",
    },
    "fruitfly_agent.lab.environment": LAB_ENV_PUBLIC_API,
    "fruitfly_agent.lab.environment.local": {"LocalEnv"},
    "fruitfly_agent.lab.catalog": {
        "ActivationScope",
        "ContextPhase",
        "MechanismLayer",
        "MechanismFamily",
        "ParameterDescriptor",
        "MechanismContribution",
        "MechanismEffects",
        "MechanismDescriptor",
        "MechanismSelection",
        "MechanismDefinition",
        "LabCatalog",
        "ProviderBinding",
        "AssemblyContext",
        "AssemblyState",
        "AssemblyResult",
        "assemble_lab",
        "builtin_catalog",
    },
    "fruitfly_agent.run.configuration": {
        "DEFAULT_HARNESS_CONFIG_NAME",
        "HARNESS_PROFILE_SCHEMA_VERSION",
        "HarnessConfig",
        "HarnessProfile",
        "load_harness_config",
        "save_harness_config",
    },
    "fruitfly_agent.lab.context_manager.augmentation.information": {
        "INFORMATION_BLOCK_END",
        "INFORMATION_BLOCK_START",
        "INFORMATION_CUSTOM_KIND",
        "InformationAccessError",
        "InformationArtifact",
        "InformationDescriptor",
        "InformationEffect",
        "InformationHit",
        "InformationQuery",
        "InformationRef",
        "InformationSearchResult",
        "InformationSpaceDescriptor",
        "InformationApplicator",
        "InformationArtifactSource",
        "InformationPostProcessor",
        "InformationQueryBuilder",
        "InformationReader",
        "InformationRetriever",
        "InformationSpace",
        "InformationSpaceCatalog",
        "StaticInformationReader",
        "CallbackInformationReader",
        "CallbackInformationRetriever",
        "LexicalRetriever",
        "BudgetedPostProcessor",
        "create_static_lexical_space",
        "TextInformationApplicator",
        "LatestUserQueryBuilder",
        "InformationPipeline",
        "InformationHub",
        "FileMemorySource",
        "FileMemoryRetriever",
        "LocalKnowledgeSource",
        "LiveHttpRetriever",
        "create_file_memory_space",
        "create_local_knowledge_space",
        "create_live_http_space",
    },
    "fruitfly_agent.lab.context_manager.augmentation.information.pipeline": {
        "LatestUserQueryBuilder",
        "InformationPipeline",
    },
    "fruitfly_agent.lab.context_manager.augmentation.information.hub": {"InformationHub"},
    "fruitfly_agent.lab.context_manager.augmentation.information.file_memory": {
        "FileMemorySource",
        "FileMemoryRetriever",
        "create_file_memory_space",
    },
    "fruitfly_agent.lab.context_manager.augmentation.information.local_knowledge": {
        "LocalKnowledgeSource",
        "create_local_knowledge_space",
    },
    "fruitfly_agent.lab.context_manager.augmentation.information.live_http": {
        "LiveHttpRetriever",
        "create_live_http_space",
    },
    "fruitfly_agent.core.loop": {"run_agent_loop", "AgentLoopContext"},
    "fruitfly_agent.core.config": {
        "AgentLoopConfig",
        "ToolExecutionConfig",
        "BeforeToolCallResult",
        "PrepareNextTurnResult",
    },
    "fruitfly_agent.core.tool_runtime": {"AgentTool", "ToolCallContext"},
    "fruitfly_agent.core.tool_runtime.schema": {"validate_tool_arguments"},
    "fruitfly_agent.providers.anthropic": {"AnthropicProvider", "classify_error"},
    "fruitfly_agent.providers.openai": {"OpenAIProvider", "classify_error"},
    "fruitfly_agent.core.data_model.runtime": {
        "AgentLoopContext",
        "ProviderView",
        "BeforeToolCallResult",
    },
    "fruitfly_agent.core.data_model.context": {
        "ContextTrigger",
        "ContextItem",
        "ContextSnapshot",
        "ContextDecision",
    },
    "fruitfly_agent.core.model_stream": {
        "AssistantMessageEventStream",
        "StreamEvent",
        "StreamStart",
        "TextDelta",
        "ThinkingDelta",
        "ToolCallStart",
        "ToolCallDelta",
        "ToolCallEnd",
        "StreamDone",
        "StreamError",
        "scripted_stream",
    },
    "fruitfly_agent.core.extensions.protocols": {
        "Provider",
        "SessionLike",
        "PrepareNextTurnResult",
        "ProviderView",
        "AgentLoopContext",
        "ExecutionEnv",
        "FileSystem",
        "Shell",
    },
    "fruitfly_agent.core.extensions.hooks": {
        "HookRegistry",
        "BEFORE_RUN",
        "BEFORE_REQUEST",
        "AFTER_RESPONSE",
        "BEFORE_TOOL",
        "AFTER_TOOL",
        "BEFORE_COMPACTION",
        "BEFORE_RUN_END",
        "BeforeRunEvent",
        "BeforeRequestEvent",
        "AfterResponseEvent",
        "ToolEvent",
        "AfterToolEvent",
        "BeforeCompactionEvent",
        "BeforeRunEndEvent",
    },
    # lab install surfaces are stable by the same rule
    "fruitfly_agent.core.context": {
        "ContextPipeline",
        "ContextPipelineProfile",
        "ContextPhase",
        "ContextProvenance",
        "ContextFrame",
        "ContextTransform",
        "ContextTransformer",
        "ContextStage",
    },
    "fruitfly_agent.lab.context_manager.reduction.summarizing": {
        "SummarizingCompactor",
        "SummarizingCompactorConfig",
        "install",
    },
    "fruitfly_agent.lab.context_manager.augmentation.skills.catalog": {
        "Skill",
        "LoadResult",
        "load_skills",
        "render_skills_xml",
    },
    "fruitfly_agent.lab.tools.builtin": {"builtin_tools"},
    "fruitfly_agent.lab.tools.read": {"create_read_tool"},
    "fruitfly_agent.lab.tools.bash": {"create_bash_tool"},
    "fruitfly_agent.lab.tools.edit": {"create_edit_tool"},
    "fruitfly_agent.lab.tools.write": {"create_write_tool"},
    "fruitfly_agent.lab.tools.ipython": {"create_ipython_tool"},
    "fruitfly_agent.lab.context_manager.augmentation.information.adapter": {
        "InformationRecallTiming",
        "InformationRecallTransformer",
        "install_information_recall",
    },
    "fruitfly_agent.lab.context_manager.augmentation.skills": {
        "Skill", "LoadResult", "load_skills", "render_skills_xml", "SkillCatalogTransformer",
    },
    "fruitfly_agent.lab.rsi": {
        "AgentVersion", "Candidate", "Verification", "EvolutionBudget",
        "EvolutionOutcome", "EvolutionAttempt", "EvolutionResult", "EvolutionDriver",
        "CandidateGenerator", "CandidateVerifier", "CandidateAdopter",
    },
    "fruitfly_agent.interactive": {
        "AgentApplication",
        "ApplicationState",
        "ConfigurationParameter",
        "ConfigurationMechanism",
        "ConfigurationSnapshot",
        "ConfigurationActionResult",
        "ConfigurationController",
        "FrontendEvent",
        "InteractiveEvent",
        "RunStarted",
        "RunActivityChanged",
        "AssistantTextDelta",
        "AssistantThinkingDelta",
        "ToolStarted",
        "ToolOutput",
        "ToolFinished",
        "CompactionStarted",
        "RunFinished",
        "EventSink",
        "LineEditor",
        "InteractiveSession",
        "InteractiveMechanism",
        "InteractiveStatus",
        "ResumableSession",
        "RuntimeFactory",
        "RuntimeHandle",
        "TerminalFrontend",
        "TerminalConfigurationFrontend",
        "TerminalRenderer",
        "TerminalResumeFrontend",
    },
    "fruitfly_agent.run": {
        "RuntimeAssembly",
        "RuntimeManifest",
        "RunApplicationFactory",
        "build_runtime",
        "HarnessSelection",
        "RunConfigurationController",
        "default_model_catalog_path",
        "model_catalog_path",
        "resolve_harness_selection",
        "resolve_profile_models",
        "create_parser",
        "resolve_session_path",
        "run_cli",
        "main",
    },
}
