"""Renderer-neutral interaction boundary and the built-in terminal frontend."""

from .optimization import TaskPackView, CorrectionView, TaskPackClient, TaskPackService, OptimizationPreview, CandidateView, OptimizationService, CandidateActivationService, CandidateActivationClient

from .application import (
    AgentApplication,
    ApplicationState,
    RuntimeFactory,
    RuntimeHandle,
)
from .configuration import (
    ConfigurationActionResult,
    ConfigurationController,
    ConfigurationLaunchResult,
    ConfigurationMechanism,
    ConfigurationSelectionGroup,
    ConfigurationParameter,
    ConfigurationSnapshot,
)
from .events import (
    AssistantTextDelta,
    AssistantThinkingDelta,
    CompactionStarted,
    FrontendEvent,
    InteractiveEvent,
    RunActivityChanged,
    RunFinished,
    RunStarted,
    ToolFinished,
    ToolOutput,
    ToolStarted,
    event_from_dict,
)
from .evaluation import (
    EvaluationBenchmarkOption,
    EvaluationController,
    EvaluationEventSink,
    EvaluationLaunchRequest,
    EvaluationLaunchResult,
    EvaluationMechanismOption,
    EvaluationModeOption,
    EvaluationSnapshot,
    EvaluationVariantOption,
)
from .dispatch import EventSink
from .models import InteractiveMechanism, InteractiveStatus, ResumableSession
from .session import InteractiveSession
from .terminal import (
    LineEditor,
    TerminalConfigurationFrontend,
    TerminalEvaluationFrontend,
    TerminalFrontend,
    TerminalRenderer,
    TerminalResumeFrontend,
)

__all__ = [
    "TaskPackView",
    "CorrectionView",
    "TaskPackClient",
    "TaskPackService",
    "OptimizationPreview",
    "CandidateView",
    "OptimizationService",
    "CandidateActivationService",
    "CandidateActivationClient",
    "AgentApplication",
    "ApplicationState",
    "RuntimeFactory",
    "RuntimeHandle",
    "ConfigurationParameter",
    "ConfigurationMechanism",
    "ConfigurationSelectionGroup",
    "ConfigurationSnapshot",
    "ConfigurationActionResult",
    "ConfigurationLaunchResult",
    "ConfigurationController",
    "EvaluationBenchmarkOption",
    "EvaluationController",
    "EvaluationEventSink",
    "EvaluationLaunchRequest",
    "EvaluationLaunchResult",
    "EvaluationMechanismOption",
    "EvaluationModeOption",
    "EvaluationSnapshot",
    "EvaluationVariantOption",
    "FrontendEvent",
    "InteractiveEvent",
    "event_from_dict",
    "RunStarted",
    "RunActivityChanged",
    "AssistantTextDelta",
    "AssistantThinkingDelta",
    "ToolStarted",
    "ToolOutput",
    "ToolFinished",
    "CompactionStarted",
    "RunFinished",
    "EventSink",
    "LineEditor",
    "InteractiveSession",
    "InteractiveMechanism",
    "InteractiveStatus",
    "ResumableSession",
    "TerminalFrontend",
    "TerminalConfigurationFrontend",
    "TerminalEvaluationFrontend",
    "TerminalRenderer",
    "TerminalResumeFrontend",
]
